EXEC = proj2
CC = g++
CFLAGS = -c -Wall

# $(EXEC) has the value of shell variable EXEC, which is run.
# #  run depends on the files main.o heap.o
$(EXEC) :main.o graph.o heap.o util.o	
# run is created by the command g++ -o run main.o heap.o
	$(CC) -o $(EXEC) main.o graph.o heap.o util.o

# main.o depends on the files main.h main.cpp
# main.o is created by the comman g++ -c -Wall main.cpp
main.o	:main.cpp 
	$(CC) $(CFLAGS) main.cpp	
	
graph.o :graph.h graph.cpp 		
	$(CC) $(CFLAGS) graph.cpp

heap.o	:heap.h heap.cpp
	$(CC) $(CFLAGS) heap.cpp

util.o :util.h util.cpp
	$(CC) $(CFLAGS) util.cpp
 				
clean	:
	rm *.o
